### ISSUE TITLE
Quark Compat crashes on opening a door. 

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [ChaoticTrials/UtilitiX#55] opened 2024-01-21 03:52 UTC
### Minecraft version

1.20.1

### LibX version

LibX-1.20.1-5.0.12

### UtilitiX version

1.20.1-0.8.9

### Forge version

47.2.19

### The latest.log file

https://gist.github.com/ZephyrWindSpirit/45d163ff595f51f4b1a49f185d4c73ab

### Issue description

https://github.com/VazkiiMods/Quark/issues/4604#issue-2092405140

### Steps to reproduce

Create world. 
Open door. 
crash. 

### Other information

Quark's classes have all changed according to the quark devs.

**Comment by MelanX** [comment] 2024-01-21 04:46
Duplicate of #54.
Can’t fix it at the moment because of other issues. I wish I could :(

**Closed as not planned by MelanX** 2024-01-21 04:46 UTC
Labels: bug
